### ISSUE TITLE
Make match score configurable

### ISSUE THREAD

**Issue by tomek199** [tomek199/elo-rating#103]
Make match score configurable depends on the kind of chosen sport. 
- [x] improve algorithm implementation to allows another score configuration
- [x] make changes on core side
- - [x] winner check
- - [x] allow draws
- - [x] update player's statistics
- - [x] revert draw match
- - [x] update opponent statistics
- [x] update league-edit component by proper "score edit" section
- [x] update match-save component to support flexible score
- [x] update player-cell component to show draw match
- [x] add draws column to opponent stats table
- [x] update forecast
- [x] update ranking by draws column
- [x] refactoring

**Comment by tomek199** [comment]
League-edit component has been added. 
Now it is possible to change the league name only. 

Next step is: add some section to make league's match score configurable. 
Feel free to put your ideas how we can represent match scores.

**Comment by Doommaker** [comment]
The best and quickest solution for now is just to put there input for score, do you can put there for example 5-2 score (this would solve most od the cases, especially for games like FIFA). However, it depends if your elo algorithm implementation supportu duch results like 5-2, etc.
