### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by tomek199** [tomek199/elo-rating#109]
Players that are added by someone to play match should get email notification. Also It would be nice to have some other kinds of notification from site, that match will begin i x-time (email, sms, pigeon, anything ;) )

Proposed by @Irrelewantny

**Comment by tpokora** [comment]
**To do:**
- [ ] Match date notification template
- [ ] Match date object class
- [ ] Handle sending in MatchService
- [ ] Send during adding to queue and edit match time
