### ISSUE TITLE
Add block layer with spinner

### ISSUE THREAD

**Issue by tomek199** [tomek199/elo-rating#13]
Add block layer directive during sending http Ajax requests. In angular 1 it could be done by interceptors.
Example: 
**Interceptor:** 
`app.factory 'httpInterceptor', [
  '$q'
  ($q) ->
    {
      request: (config) ->
        config
      response: (result) ->
        result
      responseError: (error) ->
        error
    }
]
$httpProvider.interceptors.push('httpInterceptor')
`

**Directive:** 
`app.directive "scBlock", [
  '$http'
  ($http) ->
    restrict: "E"
    templateUrl: "directives/scBlock.html"
    link: (scope) ->
      scope.$watch (->
        $http.pendingRequests.length
      ), (pendingRequests) ->
        if pendingRequests > 0
          scope.isPending = true
        else
          scope.isPending = false
]`

**Comment by tomek199** [comment]
As it's described here http://stackoverflow.com/questions/35498456/what-is-httpinterceptor-equivalent-in-angular2, there is no equivalent for interceptors in Angular 4.

**Comment by tpokora** [comment]
https://stackoverflow.com/questions/38144655/angular-2-loader-on-each-http-request

**Comment by tpokora** [comment]
Implemented very basic spinner using ngSwitch for testing. Probably will change to using observable.

**Comment by tomek199** [comment]
SpinnerComponent usage:
`<app-spinner [resource]="someResource"></app-spinner>`
Spinner will be displayed until _someResource === undefined_.
