### ISSUE TITLE
Move queue dropdown to always visible element

### ISSUE THREAD

**Issue by tpokora** [tomek199/elo-rating#51]
Refactoring of daily queue to use Match objects and by removing Queue model will be done under this task.

Quick review what needs to be done:

- [x]  Remove Queue model
- [x]  Get queue matches by get request for uncompleted matches
- [x]  Queue dropdown only showing queue matches
- [x]  Move adding match too match add component.
- [x]  Add "Queue/Complete" checkbox to add match component.
- [x]  Add time to match in queue in match add component if Queue checkbox checked

Update this comment what needs to be done

**Comment by tomek199** [comment]
Yes, it's too problematic to fix all issues related to dropdown. It will be better to make queue as a "normal" component (e.g. as match-list) and put it on the top of dashboard.

**Comment by tpokora** [comment]
Refactoring of daily queue to use Match objects and by removing Queue model will be done under this task.

Quick review what needs to be done:
1. Remove Queue model
2. Get queue matches by get request for uncompleted matches
3. Move adding match too queue to different component.
4. Queue dropdown only showing queue matches
5. Add "Queue/Complete" checkbox to add match component.

**Comment by tomek199** [comment]
HI @tpokora, 
2. you can use request `/leagues/123abc456/scheduled-matches?sort=asc` to get queue matches. 
It's already available on heroku.
