### ISSUE TITLE
Persist selected page size for completed matches

### ISSUE THREAD

**Issue by szymon-depta** [tomek199/elo-rating#62]
Save the selected page size in a cookie (in the setPageSize method)? Read it back from the cookie (ngOnInit)?
No idea whether that is possible.

Should be done for the global matches list and player's matches.

Todo:
- [x] Refactoring: move util components to separate folder.
- [x] Split 'page-size' to separate component
- [x] Read/write page size from cookies.
- [x] Add popup with cookies policy

**Comment by tomek199** [comment]
Great idea :+1:. 
It can be done e.g. by library: https://www.npmjs.com/package/ng2-cookies.
