### ISSUE TITLE
Responsive components

### ISSUE THREAD

**Issue by tomek199** [tomek199/elo-rating#78]
Add additional css classes (`col-sm-*`, `col-md-*`...) to make components responsive for mobile browsers. 

https://v4-alpha.getbootstrap.com/layout/grid/

**Comment by tpokora** [comment]
- [ ] Main page
- [ ] League dashboard
- [ ] Matches
- [ ] Add Match
- [ ] Players 
- [ ] Player 
- [ ] League settings
- [ ] Profile
