### ISSUE TITLE
Opponets tab shows statistics with disabled users

### ISSUE THREAD

**Issue by Irrelewantny** [tomek199/elo-rating#85]
When user goes to Opponents tab on player account it sees the statistics for user which are currently marked as disabled. It should shows only statistics for active users.

**Comment by szymon-depta** [comment]
It's not a bug, it's a feature ;)
But seriously - I have this written down somewhere, just didn't have time to do this.
I'll probably introduce a checkbox to show/hide stats against disabled players - I'd like to keep the possibility to see matches against disabled players too.
Will also hide players, against whom no matches were played.
